// src/react/src/component/NotificationButton.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { Bell, X } from 'react-feather';

import { MessageCard } from './MessageCard';
import { NotificationButtonProps, stylesProp } from '../types';
import { getStylesData } from '../hooks/useFetch';
import useInfiniteScrolling from '../hooks/useInfiniteScrolling';
import { Shade } from '../utils';

export const NotificationButton = ({
	apiKey,
	id,
	isDev,
	isLocal,
	position,
	messageBoxStyles,
	containerStyles,
	headerStyles,
	textStyles,
	ruleStyles,
}: NotificationButtonProps) => {
	const [clicked, setClicked] = useState(false);
	const [pageNum, setPageNum] = useState(1);
	const [stylesData, setStylesData] = useState<stylesProp>();

	const titleTextColor = Shade(stylesData?.titleBarBgColor) === 'light' ? '#000' : '#fff';
	const boxTextColor = Shade(stylesData?.notificationBgColor) === 'light' ? '#000' : '#fff';

	const toggle = () => setClicked((p) => !p);

	const BASE_URL = isDev
		? 'https://dev.mok.one'
		: isLocal
		? 'http://localhost:8080'
		: 'https://live.mok.one';

	const {
		data: messages,
		loading,
		error,
		hasMore,
	} = useInfiniteScrolling(BASE_URL, apiKey, id, pageNum, 10);

	const observer = useRef<any>();
	const lastElem = useCallback(
		(node: any) => {
			if (loading) return;

			if (observer.current) observer.current.disconnect();

			observer.current = new IntersectionObserver((entries) => {
				if (entries[0].isIntersecting && hasMore) {
					setPageNum((prev) => prev + 1);
				}
			});

			if (node) observer.current.observe(node);
		},
		[loading, hasMore]
	);

	useEffect(() => {
		getStylesData(BASE_URL, apiKey, setStylesData);
	}, []);

	return (
		<>
			<div style={{ position: 'relative', ...containerStyles }}>
				<Bell style={{ cursor: 'pointer' }} onClick={toggle}>
					Messages
				</Bell>
				{clicked && (
					<div
						style={{
							width: '300px',
							height: '350px',
							overflowY: 'scroll',
							borderRadius: '5px',
							backgroundColor: stylesData?.notificationBgColor,
							color: boxTextColor,
							boxShadow: '0 0 20px rgb(89 102 122 / 35%)',
							position: 'absolute',
							left: position === 'left' ? -278 : 0,
							right: position === 'right' ? 278 : 0,
							zIndex: '999 !important',
							...messageBoxStyles,
						}}>
						<div
							style={{
								display: 'flex',
								justifyContent: 'space-between',
								alignItems: 'center',
								backgroundColor: stylesData?.titleBarBgColor,
								color: titleTextColor,
								padding: '0 15px',
								fontWeight: '500',
								height: '50px',
								position: 'sticky',
								...headerStyles,
							}}>
							Notifications
							<X style={{ cursor: 'pointer' }} size={16} onClick={toggle} />
						</div>
						{!messages.length ? (
							<div style={{ display: 'flex', justifyContent: 'center', marginTop: '100px' }}>
								No Notification Yet!!
							</div>
						) : (
							<>
								{messages.map((elem: any, index: number) => {
									if (messages.length === index + 1)
										return (
											<div ref={lastElem} key={index}>
												<MessageCard
													text={JSON.parse(elem.json_data).text}
                          time={elem.createdAt}
													textColor={boxTextColor}
													textStyles={textStyles ?? {}}
													ruleStyles={ruleStyles ?? {}}
												/>
											</div>
										);
									else
										return (
											<div key={index}>
												<MessageCard
													text={JSON.parse(elem.json_data).text}
													time={elem.createdAt}
													textColor={boxTextColor}
													textStyles={textStyles ?? {}}
													ruleStyles={ruleStyles ?? {}}
												/>
											</div>
										);
								})}
								<div>{loading && 'Loading...'}</div>
							</>
						)}
					</div>
				)}
			</div>
		</>
	);
};

// src/angular/projects/mok-sdk/src/lib/components/notification-button/notification-button.component.ts
import { Component, Input, OnInit, ViewChild, ElementRef, OnDestroy, AfterViewChecked } from '@angular/core';
import { APIResponseItem, stylesProp } from '../../types';
import { StylesDataService } from '../../services/get-styles-data.service';
import { InfiniteScrollService } from '../../services/infinity-scroll.service';
import { Shade } from '../../utils';

@Component({
  selector: 'lib-notification-button',
  templateUrl: './notification-button.component.html',
  styleUrls: ['./notification-button.component.css']
})
export class NotificationButtonComponent implements OnInit, AfterViewChecked, OnDestroy  {
  @Input() apiKey!: string;
  @Input() position!: string;
  @Input() messageBoxStyles!: any;
  @Input() containerStyles!: any;
  @Input() headerStyles!: any;
  @Input() textStyles!: any;
  @Input() id!: string;
  @Input() isDev!: boolean;
  @Input() isLocal!: boolean;
  @Input() ruleStyles!: any;

  loading = true;
  error = false;
  data: APIResponseItem[] = [];
  item: any[] = [];
  hasMore = false;
  pageNo = 1;
  pageSize = 10;
  clicked = false;
  pageNum = 1;
  stylesData?: stylesProp;
  myNewContainerStyles!:object
  BASE_URL!:string
  morePage!:number

  private observer!: IntersectionObserver;
  @ViewChild('messageContainer') messageContainer!: ElementRef<HTMLElement>;
  constructor(private infiniteScrollService: InfiniteScrollService, private stylesDataService: StylesDataService, private host: ElementRef) { }

  getText(item: APIResponseItem): string {
    const jsonData = typeof item.json_data === 'string' ? JSON.parse(item.json_data) : item.json_data;
    return jsonData.text;
  }
  getTime(item: APIResponseItem): string {
    return item.createdAt;
  }

  ngOnInit(): void {
    this.myNewContainerStyles = Object.assign({position: 'relative'}, this.containerStyles)
    this.BASE_URL = this.isDev ? 'https://dev.mok.one' : this.isLocal ? 'http://localhost:4200' : 'https://live.mok.one';
    this.getInfiniteScrollData();
    this.stylesDataService
      .getStylesData(this.BASE_URL, this.apiKey)
      .then((data) => (this.stylesData = data.data))
      .catch((error) => console.error(error));
    
    this.observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting && this.hasMore) {
        this.getInfiniteScrollData();
      }
    }, this.options);
  }
  
  ngAfterViewChecked(): void {
    if(this.messageContainer){
      const cards = this.messageContainer.nativeElement.querySelectorAll('.message-card');
      if (cards.length > 0) {
        const lastCard = cards[cards.length - 1];
        this.observer.observe(lastCard);
      }
    }
  }
  
  ngOnDestroy() {
    this.observer.disconnect();
  }
  
  getInfiniteScrollData() {
    this.loading = true;
    this.error = false;
  
    this.infiniteScrollService
      .getInfiniteScrollData(this.BASE_URL, this.apiKey, this.id, this.pageNo, this.pageSize)
      .subscribe(
        (res: any) => {
          this.morePage = res.total
          if (res.data.length > 0) {
            this.data = [...this.data, ...res.data];
            this.hasMore = true;
            this.pageNo++;
          } else {
            this.hasMore = false;
          }
          this.loading = false;
        },
        (error: any) => {
          this.error = true;
          this.loading = false;
        }
      );
  }  

  get element() {
    return this.host.nativeElement;
  }
  
  options = {
    root:  this.isHostScrollable() ? this.host.nativeElement : null,
    rootMargin: '0px',
    threshold: 0.5
  };

  private isHostScrollable() {
    const style = window.getComputedStyle(this.element);
    return style.getPropertyValue('overflow') === 'auto' ||
      style.getPropertyValue('overflow-y') === 'scroll';
  }

  get titleTextColor() {
    return Shade(this.stylesData?.titleBarBgColor) === 'light' ? '#000' : '#fff';
  }
 
  get boxTextColor() {
    return Shade(this.stylesData?.notificationBgColor) === 'light' ? '#000' : '#fff';
  }

  toggle() {
    this.clicked = !this.clicked;
  }
}

<div [ngStyle]="myNewContainerStyles">
  <div style="cursor: pointer" (click)="toggle()">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9m-4.27 13a2 2 0 0 1-3.46 0"/>
    </svg>
  </div>
  <div *ngIf="clicked" class="notification-box {{ position }}" [ngStyle]="messageBoxStyles" [ngClass]="{scrollable: morePage>10}">
    <div class="notification-header" [ngStyle]="{backgroundColor: stylesData?.titleBarBgColor}">
      <div [ngStyle]="{padding: '10px', color: titleTextColor}">Notification</div>
      <button (click)="toggle()" [style]="{
        backgroundColor: stylesData?.titleBarBgColor,
        color: titleTextColor,
        borderRadius: '50%',
        padding: '6px',
        border: 'none',
        cursor: 'pointer'
      }">X</button>
    </div>
    <div class="notification-content" [ngStyle]="{backgroundColor: stylesData?.notificationBgColor}">
      <div *ngIf="data.length > 0" class="message-container" #messageContainer>
        <lib-message-card *ngFor="let item of data; let i = index" [lastElem]="i === data.length - 1 ? true : false" [messageCardProps]="{
          text: getText(item),
          time: getTime(item),
          textColor: boxTextColor,
          textStyles: textStyles,
          ruleStyles: ruleStyles
        }" [ngStyle]="ruleStyles" class="message-card"></lib-message-card>
      </div>
      <div *ngIf="!data.length && !error">
        <div [ngStyle]="{color: boxTextColor, display:'flex', justifyContent:'center', marginTop:'100px'}">
          No Notification Yet!!
        </div>
      </div>
      <div *ngIf="loading" [ngStyle]="{color: boxTextColor, textAlign: 'center'}">Loading...</div>
      <div *ngIf="error" [ngStyle]="{color: boxTextColor, textAlign: 'center'}">Error...</div>
  </div>
</div>
