// src/react/src/component/MessageCard.tsx
import React from 'react';

import { MessageCardProps } from '../types';
import { formatDate } from '../utils';

export const MessageCard = ({
	text,
	time,
	textColor,
	textStyles,
	ruleStyles,
}: MessageCardProps) => {
	return (
		<>
			<div
				style={{
					display: 'flex',
					justifyContent: 'space-between',
					alignItems: 'center',
					margin: '0 15px',
					color: textColor,
				}}>
				<p style={{ ...textStyles }}>{text}</p>
				<p style={{ fontSize: '14px', ...textStyles }}>{formatDate(time)}</p>
			</div>
			<hr style={{ opacity: '0.5', ...ruleStyles, color: textColor }} />
		</>
	);
};

// src/angular/projects/mok-sdk/src/lib/components/message-card/message-card.component.ts
import { Component, Input } from '@angular/core';
import { MessageCardProps } from '../../types';
import { formatDate } from '../../utils/format-date';
@Component({
  selector: 'lib-message-card',
  template: `
    <div
      style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin: 0 15px;
        color: {{ messageCardProps.textColor }}
      "
    >
      <p style="{{ messageCardProps.textStyles }}"> {{messageCardProps.text}} </p>
      <p style="font-size: 14px; {{ messageCardProps.textStyles }}">{{ formatDate(messageCardProps.time) }}</p>
    </div>
    <hr style="opacity: 0.5; color: {{ messageCardProps.textColor }}; {{messageCardProps.ruleStyles}}" />
  `,
})
export class MessageCardComponent {
  @Input() messageCardProps!: MessageCardProps;

  constructor() {}

  formatDate(date: String): string {
    return formatDate(date);
  }
}
