// src/vue/src/components/NotificationButton.vue
<script>
import InfiniteScroll from './InfiniteScroll.vue';
import getStylesData from '../api/getStyledData';
export default {
  name: 'NotificationButton',
  components: {
    InfiniteScroll: InfiniteScroll,
  },
  props: {
    containerStyles: {
      type: Object,
      default: () => ({}),
    },
    position: {
      type: String,
      default: () => 'right',
    },
    apiKey: {
      type: String,
      required: true,
    },
    isDev: Boolean,
    isLocal: Boolean,
    id: {
      type: String,
      required: true,
    },
    messageBoxStyles: {
      type: Object,
      default: () => ({}),
    },
    ruleStyles: {
      type: Object,
      default: () => ({}),
    },
    textStyles: {
      type: Object,
      default: () => ({}),
    },
    headerStyles: {
      type: Object,
      default: () => ({}),
    },
  },
  data() {
    return {
      clicked: false,
      stylesData: {},
    };
  },
  methods: {
    toggle() {
      this.clicked = !this.clicked;
    },
    async getUpdateStylesData() {
      try {
        const BASE_URL = this.isDev
          ? 'https://dev.mok.one'
          : this.isLocal
          ? 'http://localhost:8080'
          : 'https://live.mok.one';
        const data = await getStylesData(BASE_URL, this.apiKey);
        this.stylesData = data;
      } catch (error) {
        console.log(error)
      }
    },
  },
  created() {
    this.getUpdateStylesData()
  },
};
</script>

<template>
  <div :style="{ position: 'relative', ...this.containerStyles }">
    <div style="cursor: pointer" @click="toggle">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
      >
        <path
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9m-4.27 13a2 2 0 0 1-3.46 0"
        />
      </svg>
    </div>

    <div
      v-show="clicked"
      :style="{
        width: '300px',
        height: '350px',
        overflowY: 'none',
        borderRadius: '5px',
        backgroundColor: stylesData?.notificationBgColor,
        color: stylesData?.boxTextColor,
        boxShadow: '0 0 20px rgb(89 102 122 / 35%)',
        position: 'absolute',
        left: this.position === 'left' ? -278 : 0,
        right: this.position === 'right' ? 278 : 0,
        zIndex: '999 !important',
        ...this.messageBoxStyles,
      }"
    >
      <div
        :style="{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          backgroundColor: stylesData?.titleBarBgColor,
          color: stylesData?.titleTextColor,
          padding: '0 15px',
          fontWeight: '500',
          height: '50px',
          position: 'sticky',
          ...this.headerStyles,
        }"
      >
        Notifications
        <div style="cursor: pointer" @click="toggle">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <g
              id="feClose0"
              fill="none"
              fill-rule="evenodd"
              stroke="none"
              stroke-width="1"
            >
              <g id="feClose1" fill="currentColor">
                <path
                  id="feClose2"
                  d="M10.657 12.071L5 6.414L6.414 5l5.657 5.657L17.728 5l1.414 1.414l-5.657 5.657l5.657 5.657l-1.414 1.414l-5.657-5.657l-5.657 5.657L5 17.728z"
                />
              </g>
            </g>
          </svg>
        </div>
      </div>
      <Suspense>
        <InfiniteScroll :textStyles="textStyles" :ruleStyles="ruleStyles" :apiKey="apiKey" :id="id" :isDev="isDev" :isLocal="isLocal" :stylesData="stylesData" />
        <template #fallback>
          <p>Loading...</p>
        </template>
      </Suspense>
    </div>
  </div>
  <!-- <main
    style="
      width: 100%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    "
  >
    <h1>Infinite Scrolling Component</h1>
    <Suspense>
      <InfiniteScroll />
      <template #fallback>
        <p>Loading...</p>
      </template>
    </Suspense>
  </main> -->
</template>

// src/react/src/component/NotificationButton.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { Bell, X } from 'react-feather';

import { MessageCard } from './MessageCard';
import { NotificationButtonProps, stylesProp } from '../types';
import { getStylesData } from '../hooks/useFetch';
import useInfiniteScrolling from '../hooks/useInfiniteScrolling';
import { Shade } from '../utils';

export const NotificationButton = ({
	apiKey,
	id,
	isDev,
	isLocal,
	position,
	messageBoxStyles,
	containerStyles,
	headerStyles,
	textStyles,
	ruleStyles,
}: NotificationButtonProps) => {
	const [clicked, setClicked] = useState(false);
	const [pageNum, setPageNum] = useState(1);
	const [stylesData, setStylesData] = useState<stylesProp>();

	const titleTextColor = Shade(stylesData?.titleBarBgColor) === 'light' ? '#000' : '#fff';
	const boxTextColor = Shade(stylesData?.notificationBgColor) === 'light' ? '#000' : '#fff';

	const toggle = () => setClicked((p) => !p);

	const BASE_URL = isDev
		? 'https://dev.mok.one'
		: isLocal
		? 'http://localhost:8080'
		: 'https://live.mok.one';

	const {
		data: messages,
		loading,
		error,
		hasMore,
	} = useInfiniteScrolling(BASE_URL, apiKey, id, pageNum, 10);

	const observer = useRef<any>();
	const lastElem = useCallback(
		(node: any) => {
			if (loading) return;

			if (observer.current) observer.current.disconnect();

			observer.current = new IntersectionObserver((entries) => {
				if (entries[0].isIntersecting && hasMore) {
					setPageNum((prev) => prev + 1);
				}
			});

			if (node) observer.current.observe(node);
		},
		[loading, hasMore]
	);

	useEffect(() => {
		getStylesData(BASE_URL, apiKey, setStylesData);
	}, []);

	return (
		<>
			<div style={{ position: 'relative', ...containerStyles }}>
				<Bell style={{ cursor: 'pointer' }} onClick={toggle}>
					Messages
				</Bell>
				{clicked && (
					<div
						style={{
							width: '300px',
							height: '350px',
							overflowY: 'scroll',
							borderRadius: '5px',
							backgroundColor: stylesData?.notificationBgColor,
							color: boxTextColor,
							boxShadow: '0 0 20px rgb(89 102 122 / 35%)',
							position: 'absolute',
							left: position === 'left' ? -278 : 0,
							right: position === 'right' ? 278 : 0,
							zIndex: '999 !important',
							...messageBoxStyles,
						}}>
						<div
							style={{
								display: 'flex',
								justifyContent: 'space-between',
								alignItems: 'center',
								backgroundColor: stylesData?.titleBarBgColor,
								color: titleTextColor,
								padding: '0 15px',
								fontWeight: '500',
								height: '50px',
								position: 'sticky',
								...headerStyles,
							}}>
							Notifications
							<X style={{ cursor: 'pointer' }} size={16} onClick={toggle} />
						</div>
						{!messages.length ? (
							<div style={{ display: 'flex', justifyContent: 'center', marginTop: '100px' }}>
								No Notification Yet!!
							</div>
						) : (
							<>
								{messages.map((elem: any, index: number) => {
									if (messages.length === index + 1)
										return (
											<div ref={lastElem} key={index}>
												<MessageCard
													text={JSON.parse(elem.json_data).text}
                          time={elem.createdAt}
													textColor={boxTextColor}
													textStyles={textStyles ?? {}}
													ruleStyles={ruleStyles ?? {}}
												/>
											</div>
										);
									else
										return (
											<div key={index}>
												<MessageCard
													text={JSON.parse(elem.json_data).text}
													time={elem.createdAt}
													textColor={boxTextColor}
													textStyles={textStyles ?? {}}
													ruleStyles={ruleStyles ?? {}}
												/>
											</div>
										);
								})}
								<div>{loading && 'Loading...'}</div>
							</>
						)}
					</div>
				)}
			</div>
		</>
	);
};
